
server:
  port:
    9000

logging:
  level:
      - org.springframework: DEBUG


spring:
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: http://localhost:8080
          predicates:
            - Method=POST
            - Path=/api/v1/auth
            